backend:
  name: github
  repo: Coders-Beyond-Bars/website_gatsby
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "about"
    label: "About"
    folder: "src/pages/about"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
      - {label: "Path", name: "path", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "work"
    label: "Work"
    folder: "src/pages/work"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "work-page"}
      - {label: "Path", name: "path", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "connect"
    label: "Connect"
    folder: "src/pages/connect"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "connect-page"}
      - {label: "Path", name: "path", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
